services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: lokaltorget
      POSTGRES_PASSWORD: lokaltorget
      POSTGRES_DB: lokaltorget
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgresql://lokaltorget:lokaltorget@db:5432/lokaltorget
      SECRET_KEY: 1e67481aca087217263141916ece6b6a06c92b27b65aa5965c16ba2a763d0771
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata: